source 'https://rubygems.org'
ruby '2.2.2'
gem 'rails'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'rails_12factor'
gem 'bootstrap-sass'
gem 'high_voltage'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'therubyracer', :platform=>:ruby
gem 'figaro'
gem 'koala'
gem 'rmagick'
gem 'better_errors'
gem 'unirest'
gem 'simple_form', '~> 3.2', '>= 3.2.1'
gem 'acts_as_votable', '~> 0.10.0'
gem 'redcarpet'
gem 'coderay'
gem 'phantomjs', '~> 2.1', '>= 2.1.1.0'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'byebug'
  gem 'spring'
  gem 'sqlite3'
end
group :production do
  gem 'puma'
  gem 'pg'
end
